title: "Dr. Caleb H. Kelley"
email: caleb.kelley@emory.edu
description: >-
  Visiting Assistant Professor at Emory University. Researching language variation, sociolinguistics, and the sounds of social meaning.
baseurl: ""
url: "https://calebhkelley.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"


# Site Author
author:
  name: "Dr. Caleb Kelley"
  bio: "Visiting Assistant Professor<br/>Department of Spanish and Portuguese<br/>Emory University"
  location: "Atlanta, GA"
  avatar: "/assets/images/caleb-kelley-headshot.jpeg"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:caleb.kelley@emory.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/caleb-kelley-ph-d-309081aa/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/calebhkelley"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-1425-6002"

# Site navigation
masthead_title: "Caleb H. Kelley, Ph.D."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

include:
  - _pages

# Outputting
permalink: /blog/:title/
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      show_date: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false


# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/