title: "Dr. Caleb H. Kelley"
email: caleb.kelley@emory.edu
description: >-
  Visiting Assistant Professor at Emory University. Researching language variation, sociolinguistics, and the sounds of social meaning.
baseurl: ""
url: "https://calebhkelley.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

# Site Author
author:
  name: "Dr. Caleb Kelley"
  bio: "Visiting Assistant Professor<br/>Department of Spanish and Portuguese<br/>Emory University"
  location: "Atlanta, GA"
  avatar: "/assets/images/bio-photo.jpg"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:caleb.kelley@emory.edu"

# Site navigation
masthead_title: "Caleb H. Kelley, Ph.D."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
